### PR TITLE
DPPA-383 Add notebook with cumulative scan example.

### PR DESCRIPTION
**Pull request by rfinck**

### CODE REVIEW

**Comment by stanislaw-ionpath** [comment]
@rfinck This looks great! One thinng I do not understand. Are the multi-depth images prealigned?

**Comment by stanislaw-ionpath** [comment]
@rfinck could you mention somewhere in the notebook that tiff images should be saved with alignment?

**Comment by murataksoy** [comment]
Thanks @rfinck , this looks great. I guess we should coordinate and release these both (MIBI/O and mibitracker-client) soon since MSK seemed to need this asap.

A small comment: Reading the individual depth images could also be made into a function.

**Comment by rfinck** [comment]
Thanks @stanislaw-ionpath and @murataksoy I made the changes you suggested.

**Pull request merged**
