### PR TITLE
DPPA-869 Add refresh route and default to automatically call it every 5 minutes.

### PR DESCRIPTION
**Pull request by rfinck**
This enables a token to be refreshed so it stays valid during a long-running (hours) script, and becomes more necessary as default token expiration times get shorter. They are anticipated to become 45 minutes in the near future.

### CODE REVIEW

**Comment by rfinck** [comment]
@yari-ionpath pillow is a dependency of skimage, and under the hood the version that was being installed changed, resulting in tests failing that also indicate this would be a failure in normal usage. You are right that it's not clear why it's part of this PR (this just happens to be the first PR since that change), so I will follow better practices than I did here and put up a separate PR that if it's merged first can prevent this one from failing.

**Comment by rfinck** [comment]
@yari-ionpath This needs another review now that I reverted those unrelated commits.

**Comment by yari-ionpath** [comment]
great. thanks for the explanation (and setting a good example for task specific PRs!)

**Comment by rfinck** [comment]
@jaytarolli I am going to merge this, but will wait to tag a release until you've confirmed you don't need additional changes for your dependencies.

**Pull request merged**
